---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/tasks":
    get:
      summary: "#Index"
      tags:
      - Task
      parameters:
      - name: status
        in: query
        required: false
        schema:
          type: string
      - name: text
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: successful
servers:
- url: "{defaultHost}"
  variables:
    defaultHost:
      default: http://localhost:3000/
