---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/tasks":
    get:
      summary: "#Index"
      tags:
      - Task
      parameters:
      - name: status
        in: query
        required: false
        schema:
          type: string
      - name: text
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: successful
  "/tasks/{id}":
    get:
      summary: "#Show"
      tags:
      - Task
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: successful
    put:
      summary: "#Update"
      tags:
      - Task
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                task:
                  type: object
                  properties:
                    name:
                      type: string
                      example: LLC
                    description:
                      type: string
                      example: voluptates
                    stats:
                      type: string
                      example: done
    delete:
      summary: "#Destroy"
      tags:
      - Task
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: successful
  "/tasks/":
    post:
      summary: "#Create"
      tags:
      - Task
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                task:
                  type: object
                  properties:
                    name:
                      type: string
                      example: and Sons
                    description:
                      type: string
                      example: dicta
servers:
- url: "{defaultHost}"
  variables:
    defaultHost:
      default: http://localhost:3000/
