---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/log_in/":
    post:
      summary: "#log_in"
      tags:
      - Session
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: pedro@kuhn.io
                password:
                  type: string
                  example: 6yRqIfUi4
  "/api/v1/tasks":
    get:
      summary: "#Index"
      tags:
      - Task
      parameters:
      - name: status
        in: query
        required: false
        schema:
          type: string
      - name: text
        in: query
        required: false
        schema:
          type: string
      - name: access-token
        in: header
        schema:
          type: string
      - name: user-id
        in: header
        schema:
          type: string
      responses:
        '200':
          description: successful
  "/api/v1/tasks/{id}":
    get:
      summary: "#Show"
      tags:
      - Task
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      - name: access-token
        in: header
        schema:
          type: string
      - name: user-id
        in: header
        schema:
          type: string
      responses:
        '200':
          description: successful
    put:
      summary: "#Update"
      tags:
      - Task
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      - name: access-token
        in: header
        schema:
          type: string
      - name: user-id
        in: header
        schema:
          type: string
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                task:
                  type: object
                  properties:
                    name:
                      type: string
                      example: LLC
                    description:
                      type: string
                      example: adipisci
                    stats:
                      type: string
                      example: done
    delete:
      summary: "#Destroy"
      tags:
      - Task
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      - name: access-token
        in: header
        schema:
          type: string
      - name: user-id
        in: header
        schema:
          type: string
      responses:
        '200':
          description: successful
  "/api/v1/tasks/":
    post:
      summary: "#Create"
      tags:
      - Task
      parameters:
      - name: access-token
        in: header
        schema:
          type: string
      - name: user-id
        in: header
        schema:
          type: string
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                task:
                  type: object
                  properties:
                    name:
                      type: string
                      example: Group
                    description:
                      type: string
                      example: quo
  "/api/v1/users":
    get:
      summary: "#Index"
      tags:
      - User
      responses:
        '200':
          description: successful
  "/api/v1/users/{id}":
    get:
      summary: "#Show"
      tags:
      - User
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: successful
    put:
      summary: "#Update"
      tags:
      - User
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      - name: access-token
        in: header
        schema:
          type: string
      - name: user-id
        in: header
        schema:
          type: string
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      example: annalee@hansen.io
                    password:
                      type: string
                      example: UzNa09IoV
    delete:
      summary: "#Destroy"
      tags:
      - User
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      - name: access-token
        in: header
        schema:
          type: string
      - name: user-id
        in: header
        schema:
          type: string
      responses:
        '200':
          description: successful
  "/api/v1/users/":
    post:
      summary: "#Create"
      tags:
      - User
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      example: charlie@bosco.name
                    password:
                      type: string
                      example: QhI60aQq
servers:
- url: "{defaultHost}"
  variables:
    defaultHost:
      default: http://localhost:3000/
